Revert "CS-906. Added notifications about requested/rejected propose to close Escrow." due to following exception:
[191225 00:36:59 ERROR /opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/django/utils/log.py:228|django.request] Internal Server Error: /api/v1/escrows/d1debd3f-c3bc-4f28-aa8b-9761754a2248/accept/                                                                                                                         Traceback (most recent call last):                                                                                                                                                File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner                                  response = get_response(request)                                                                                                                                              File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response                              response = self.process_exception_by_middleware(e, request)                                                                                                                   File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response                              response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                                       File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view                             return view_func(*args, **kwargs)                                                                                                                                             File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view                                         return self.dispatch(request, *args, **kwargs)                                                                                                                                File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)                                                                                                                                         File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception                                self.raise_uncaught_exception(exc)                                                                                                                                            File "/opt/dev-application/django-app-20191225003358/.venv/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch                                        response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/dev-application/django-app-20191225003358/frontend_api/views/escrow.py", line 215, in accept
    notify_counterpart_about_escrow_state(
NameError: name 'notify_counterpart_about_escrow_state' is not defined

This reverts commit 69d7cc1815a2ba9800fe75fa06211d3430239b46.